services:
  web:
    container_name: frontend
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - app-net

networks:
  app-net:
    external: true